<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'test1' => [
        'type' => 'cache',
        'driver' => 'redis',
        'host' => 'localhost',
        'port' => 6379,
        'pass' => 'aeshia',
        'user' => 'asdgah'
    ],
    'i18n' => [
        'type' => 'cache',
        'driver' => 'redis',
        'host' => 'localhost',
        'port' => 6379,
        'pass' => NULL,
        'user' => NULL,
        'database' => 10
    ],
    'cache2' => [
        'type' => 'cache',
        'driver' => 'memcached',
        'host' => 'localhost',
        'port' => 9382
    ],
    'cache3' => [
        'type' => 'cache',
        'driver' => 'memcached',
        'host' => 'another.host.com',
        'port' => 11211
    ],
    'cache4' => [
        'type' => 'cache',
        'driver' => 'memcached',
        'host' => '4125',
        'port' => 11211
    ],
    'cache5' => [
        'type' => 'cache',
        'driver' => 'memcached',
        'host' => 'hostname.host.com',
        'port' => 7485
    ],
    'cache6' => [
        'type' => 'cache',
        'driver' => 'redis',
        'host' => 'localhost',
        'port' => 6379,
        'database' => 2,
        'ttl' => 9685
    ]
];
