<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'type' => 'filesystem',
    'config' => [
        [
            'name' => 'sftp1',
            'driver' => 'sftp',
            'host' => 'fdhfkjs',
            'root' => 'asdfas',
            'username' => 'fadfs',
            'password' => 'asfd',
            'port' => 22,
            'timeout' => 30,
            'pkey' => null,
            'passkey' => null,
            'max_tries' => 10,
            'fingerprint' => null,
            'systemType' => null,
            'mod' => [
                'file' => [
                    'public' => 0640,
                    'private' => 0604
                ],
                'dir' => [
                    'public' => 0740,
                    'private' => 0604
                ]
            ]
        ],
        [
            'name' => 'sftp3',
            'driver' => 'sftp',
            'host' => 'trying.test.com',
            'root' => 'gasdg ashshs',
            'username' => 'fadfs',
            'password' => 'asfd',
            'port' => 22,
            'timeout' => 30,
            'pkey' => null,
            'passkey' => null,
            'max_tries' => 10,
            'fingerprint' => null,
            'systemType' => null,
            'mod' => [
                'file' => [
                    'public' => 0640,
                    'private' => 0604
                ],
                'dir' => [
                    'public' => 0740,
                    'private' => 0604
                ]
            ]
        ]
    ]
];
