<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'sftp1' => [
        'type' => 'sftp',
        'host' => 'fdhfkjs',
        'root' => 'asdfas',
        'username' => 'fadfs',
        'password' => 'asfd',
        'port' => 22,
        'timeout' => 30,
        'pkey' => null,
        'passkey' => null,
        'max_tries' => 10,
        'fingerprint' => null,
        'systemType' => null,
        'mod' => [
            'file' => [
                'public' => '0640',
                'private' => '0604'
            ],
            'dir' => [
                'public' => '0740',
                'private' => '7604'
            ]
        ]
    ],
    'sftp3' => [
        'type' => 'sftp',
        'host' => 'fasdfads hgsdg dasghas',
        'root' => 'gasdg ashshs',
        'username' => 'fadfs',
        'password' => 'asfd',
        'port' => 22,
        'timeout' => 30,
        'pkey' => null,
        'passkey' => null,
        'max_tries' => 10,
        'fingerprint' => null,
        'systemType' => null,
        'mod' => [
            'file' => [
                'public' => '0640',
                'private' => '0604'
            ],
            'dir' => [
                'public' => '0740',
                'private' => '7604'
            ]
        ]
    ]
];
