<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'type' => 'jwt',
    'aud' => 'das',
    'cty' => 'fsda',
    'exp' => 3600,
    'iss' => NULL,
    'nbf' => 0,
    'pass' => '78162   37\\c2y rwg7f9sda f bko7q8fad'
];
