<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'teste' => [
        'type' => 'queue',
        'driver' => 'redis',
        'host' => 'localhost',
        'port' => 6379,
        'pass' => '',
        'database' => 16,
        'producer' => 'Brudam',
        'processor' => 'Brudam'
    ],
    'amqp' => [
        'type' => 'queue',
        'driver' => 'rabbit',
        'host' => 'localhost',
        'vhost' => 'brd',
        'port' => 5672,
        'pass' => '',
        'exchange' => 'test.amqp',
        'queue_type' => 'topic',
        'persisted' => false,
        'producer' => 'Brudam',
        'processor' => 'Brudam'
    ]
];