<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'teste' => [
        'type' => 'queue',
        'driver' => 'redis',
        'host' => 'localhost',
        'port' => 6379,
        'pass' => '',
        'database' => 16,
        'producer' => 'Brudam',
        'processor' => 'Brudam'
    ],
    'track' => [
        'type' => 'queue',
        'driver' => 'rabbit',
        'host' => 'b-3809e3d1-ec72-4283-aa16-cdfcd2b78848.mq.us-east-1.amazonaws.com',
        'vhost' => 'services',
        'port' => 5671,
        'pass' => '',
        'exchange' => 'tracking',
        'queue_type' => 'direct',
        'persisted' => false,
        'producer' => 'Brudam',
        'processor' => 'Brudam'
    ]
];