<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'brd' => [
        'type' => 's3',
        'credentials' => [
            'key' => 'your-key',
            'secret' => 'your-secret'
        ],
        'region' => 'your-region',
        'version' => 'latest'
    ],
    'sec' => [
        'type' => 's3',
        'credentials' => [
            'key' => 'sec-key',
            'secret' => 'sec-secret'
        ],
        'region' => 'sec-region',
        'version' => 'latest'
    ]
];