<?php

/*
 * ATENTION!!!
 * File auto generated by Inspire\System\Config
 */
return [
    'warn' => [
        'type' => 'log',
        'path' => '/var/www/projects/inspire/storage/logs/',
        'name' => APP_NAME . '_' . date('Y-m-d') . '.txt',
        'format' => '[%level%: %date%] %message%',
        'date_format' => '%d/%m/%y',
        'expire' => 6
    ],
    'error' => [
        'type' => 'log',
        'path' => '/var/www/projects/inspire/storage/logs/',
        'name' => APP_NAME . '_' . date('Y-m-d') . '.txt',
        'format' => '[%level%: %date%] %message%',
        'date_format' => '%d/%m/%y',
        'expire' => 3
    ],
    'info' => [
        'type' => 'log',
        'path' => '/var/www/projects/inspire/storage/logs/',
        'name' => APP_NAME . '_' . date('Y-m-d') . '.txt',
        'format' => '[%level%: %date%] %message%',
        'date_format' => '%d/%m/%y',
        'expire' => 10
    ]
];
